version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: prod_container
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: "0000"
      POSTGRES_DB: prod_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    

volumes:
  postgres_data: