version: '3.8'

services:
  postgres:
    image: postgres:15  # 最新の PostgreSQL バージョン
    container_name: alpha_vantage_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: alpha_vantage
    ports:
      - "5432:5432"  # ローカルの 5432 ポートと紐付け
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  # データ永続化
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # 初回実行スクリプト
    networks:
      - db_alpha_vantage_network


networks:
  db_alpha_vantage_network:
    driver: bridge